name: Publish TournamentGenerator Nuget

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish TournamentGenerator NuGet package
    runs-on: ubuntu-latest
    env:
      TEST: "Test"
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/<organization>/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build solution and generate NuGet package
        run: |
          cd src
          dotnet pack -c Release 
          
      - name: Publish the package to nuget.org
        run: |
          dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
